# Cloud Build Config Structure Overview
# https://cloud.google.com/cloud-build/docs/build-config

# Useful post on bash/script syntax in cloudbuild
# https://medium.com/@davidstanke/mastering-google-cloud-build-config-syntax-8c3024607daf

steps:
# Install Python
- name: 'python:3.10'
  id: INSTALL-PYTHON
  dir: "."
  entrypoint: python3
  args:
    [
      "-m",
      "pip",
      "install",
      "-r",
      "requirements-dev.txt", # Dependencies for the service
      "--user",  # So dependencies get loaded in right place, and persist across Steps
      "--no-warn-script-location",
      "-e", # equivalent to 'pip install -e .' to install local package
      "."
    ]

# Check for secrets, tokens, etc.
- name: golang:1.17
  id: GITLEAKS-CHECK
  dir: "."
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -e
      go install github.com/zricethezav/gitleaks/v8@latest
      gitleaks detect --redact --verbose --report-path=gitleaks_report.json --report-format=json --no-git
  waitFor: [-]

# Linting
- name: 'python:3.10'
  id: BLACK-CHECK
  dir: "."
  entrypoint: python3
  args: ["-m", "black", ".", "--check"]
  waitFor:
    - INSTALL-PYTHON

- name: 'python:3.10'
  id: ISORT-CHECK
  dir: "."
  entrypoint: python3
  args: ["-m", "isort", ".", "--check-only"]
  waitFor:
    - INSTALL-PYTHON

# Run tests
- name: 'python:3.10'
  id: RUN-TESTS
  dir: "."
  entrypoint: 'bash'
  # NOTE: builder service account must have ServiceAccountTokenCreator role on Project or service account level
  args: ["./scripts/run_tests.sh"]
  waitFor:
    - INSTALL-PYTHON

# Build Python Package and Publish to Artifact Registry
- name: 'python:3.10'
  id: BUILD-PUBLISH
  dir: "."
  entrypoint: 'bash'
  args:
    - -c
    - |
      # exit when any command fails
      set -e
      # Set env vars and export (with set -a setting)
      set -a
      source scripts/set_env.sh
      set +a
      
      echo "Triggered from tag ${TAG_NAME}, building and publishing package"
      
      bash ./scripts/build_publish_package.sh

substitutions:
    _REPO_OWNER: Precis-Digital

# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#yaml_3
options:
    substitution_option: 'ALLOW_LOOSE'

timeout: 1800s