# Create GitHub Build Trigger
# https://cloud.google.com/sdk/gcloud/reference/beta/builds/triggers/create/github
# https://cloud.google.com/config-connector/docs/reference/resource-docs/cloudbuild/cloudbuildtrigger
# branch-pattern flag supports regex, can also use tag-pattern, or pull-request-pattern

description: pandabear Publish Build Trigger
filename: "./cloudbuild/cloudbuild_publish.yaml"
github:
  name: pandabear
  owner: Precis-Digital
  push:
    tag: ^v[0-9].[0-9].[0-9][a-zA-Z]*$
ignoredFiles:
- '**/*.md'
includedFiles:
- "**"
name: pandabear-prod-push-to-master
includeBuildLogs: "INCLUDE_BUILD_LOGS_WITH_STATUS"