default_context:
  __package_dir: pandabear
  __template_version: 0.0.3
  _output_dir: /Users/ulfaslak/Documents/git
  package_description: An runtime vschema validator for Pandas DataFrames.
  package_name: pandabear
  package_slug: pandabear
